name: publish

on:
  push:
    paths:
      - "src/**"
      - "addon.yaml"
      - "config.yaml"
      - "iot-link-incognito-addon.csproj"
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.x.x"
      - run: dotnet build --configuration Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          files: |
            bin/Release/net48/iot-link-incognito-addon.dll
            addon.yaml
            config.yaml
